[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my_custom_library"
version = "0.0.1"
authors = [
  { name="Your Name", email="you@example.com" },
]
description = "A short description of my custom library."