[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "physics_modules"
version = "0.0.1"
authors = [
  { name="Ben Kinvig", email="bckinvig1@sheffield.ac.uk" },
]
description = "A short description of my custom library."